# Copyright 2019 Chris Rose
exclude: >-
  (?x)^(
      vendor/.*|
      .*\.lock
  )$
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: rubocop
        exclude: >-
          (?x)^(
          bin/.*|
          db/schema.rb
          )$

  - repo: local
    hooks:
      - id: copyright-check
        name: Copyright Check
        entry: bundle exec rake test:branch:copyright
        language: system
        pass_filenames: false
        types: [text]
