version: '3.6'
# Copyright 2019 James Polley

services:
  postgres:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

  confzealand:
    build:
      context: ./
      target: development
    depends_on:
      - postgres
    image: confzealand:latest
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app
      - type: tmpfs
        target: /app/tmp
