# Copyright 2019 James Polley
# Copyright 2019 Steven C Hartley
# Copyright 2020 Matthew B. Gray
# Copyright 2021 Fred Bauer
#
# Licensed under the Apache License, Version 2.0

version: '3.7'

volumes:
  pgdata:
  redis-data:
  node_modules:

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data


          
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  web:
    entrypoint: "script/docker_web_entry.sh"
    working_dir: /hack
    image: wellington-dc:latest
    depends_on:
      - postgres
      - redis
    env_file:
      .env
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - node_modules:/hack/node_modules  # Except node_modules folder which is exclusive to the container
      - ./:/hack                         # Mount current working directory to /hack for hacking :)
      - type: tmpfs
        target: /hack/tmp

  worker:
    entrypoint: "script/docker_sidekiq_entry.sh"
    working_dir: /hack
    image: wellington-dc:latest
    depends_on:
      - web
      - postgres
      - redis
    env_file:
      .env
    restart: always
    volumes:
      - node_modules:/hack/node_modules  # Except node_modules folder which is exclusive to the container
      - ./:/hack                         # Mount current working directory to /hack for hacking :)
      - type: tmpfs
        target: /hack/tmp

  mail:
    entrypoint: "mailcatcher -f --ip 0.0.0.0"
    image: registry.gitlab.com/worldcon/wellington:latest
    depends_on:
      - web
      - worker
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
