 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cart_orders", type: :request do
  # CartOrder. As you add validations to CartOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CartOrder.create! valid_attributes
      get cart_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cart_order = CartOrder.create! valid_attributes
      get cart_order_url(cart_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cart_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cart_order = CartOrder.create! valid_attributes
      get edit_cart_order_url(cart_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CartOrder" do
        expect {
          post cart_orders_url, params: { cart_order: valid_attributes }
        }.to change(CartOrder, :count).by(1)
      end

      it "redirects to the created cart_order" do
        post cart_orders_url, params: { cart_order: valid_attributes }
        expect(response).to redirect_to(cart_order_url(CartOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CartOrder" do
        expect {
          post cart_orders_url, params: { cart_order: invalid_attributes }
        }.to change(CartOrder, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cart_orders_url, params: { cart_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cart_order" do
        cart_order = CartOrder.create! valid_attributes
        patch cart_order_url(cart_order), params: { cart_order: new_attributes }
        cart_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cart_order" do
        cart_order = CartOrder.create! valid_attributes
        patch cart_order_url(cart_order), params: { cart_order: new_attributes }
        cart_order.reload
        expect(response).to redirect_to(cart_order_url(cart_order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cart_order = CartOrder.create! valid_attributes
        patch cart_order_url(cart_order), params: { cart_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cart_order" do
      cart_order = CartOrder.create! valid_attributes
      expect {
        delete cart_order_url(cart_order)
      }.to change(CartOrder, :count).by(-1)
    end

    it "redirects to the cart_orders list" do
      cart_order = CartOrder.create! valid_attributes
      delete cart_order_url(cart_order)
      expect(response).to redirect_to(cart_orders_url)
    end
  end
end
