source "https://rubygems.org"

gem "activerecord", "~>5.2.0"
gem "pg", "~>1.0.0"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "pry-byebug"
  gem "rspec", "~> 3.8"
  gem "factory_bot", "~> 4.11"
end
