default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  timeout: <%= ENV["DB_TIMEOUT"] || 8000 %>

development:
  <<: *default
  database: worldcon_development

test:
  <<: *default
  database: worldcon_test

staging:
  <<: *default
  database: worldcon_staging

production:
  <<: *default
  database: worldcon_production
