# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Scheudle format is in cron
# more information can be found at https://crontab.guru/
schedule:
  sync_nominations_to_dave:
    cron: '10 0 * * * America/Los_Angeles' # At 00:10 every day
    class: NominationsTdsSync

  email_nomination_reports:
    cron: '10 0 * * * America/Los_Angeles' # At 00:10 every day
    class: SendNominationReports

  email_membership_reports:
    cron: '0 1 * * 6 Pacific/Auckland' # At 01:00 on Saturday
    class: SendMembershipReports

  # TODO maybe it would have been better to use this http://localhost:3000/sidekiq/scheduled
  # This job returns early if you're not close to 72 hours of nomination close
  # It runs a lot so that the reminder is timely
  email_nomination_reminder_3_days:
    cron: '0 * * * * Pacific/Auckland' # Every hour on the hour
    class: NominationReminderMassMailout

  email_nomination_ballot_summaries:
    cron: '*/30 * * * * Pacific/Auckland' # Runs every half an hour
    class: SendBallotSummaries
