# Scheudle format is in cron
# more information can be found at https://crontab.guru/
schedule:
  email_nomination_ballot_summaries:
    cron: '*/30 * * * *' # Runs every half an hour
    class: SendBallotSummaries
