# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
# Copyright 2019 Jen Zajac (jenofdoom)
# Copyright 2020, 2021 Victoria Garcia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# MembershipOffer is a representation of how to display a price of a Membership to a User
# MembershipOffer#options generates what's displayed in the shop based on Membership#active records
# MembershipOffer is used in ReservationsController to display prices, but also to check if an offer is available
# see also SetMembership
class MembershipOffer
  attr_reader :membership

  delegate :description, to: :membership

  def self.options
    Membership.active.order_by_price.map do |membership|
      MembershipOffer.new(membership)
    end
  end

  def self.locked_in_options(lock_date)
    Membership.locked_available(lock_date).order_by_price.map do |membership|
      MembershipOffer.new(membership)
    end
  end

  def self.locked_and_unlocked_options(lock_date)
    Membership.active.or(Membership.active_at(lock_date)).order_by_name.map do|membership|
      MembershipOffer.new(membership)
    end
  end

  # Takes a hashcode generated by the hash method, below.
  def self.locate_active_offer_by_hashcode(hashcode)
    options.select { |o| o.hash == hashcode }.first
  end

  def self.located_locked_active_offer_by_hashcode(hashcode, lock_date)
    locked_in_options(lock_date).select { |o| o.hash == hashcode }.first
  end

  def initialize(membership)
    @membership = membership
  end

  def to_s
    "#{membership} #{formatted_price}"
  end

  # Compute a hash-code for this hash. Two offers with the same content will have the same hash code.
  def hash
    "#{membership} #{formatted_price}"
  end

  def formatted_price
    if membership.price.positive?
      membership.price.format(with_currency: true)
    else
      "Free"
    end
  end

  def name
    membership.to_s
  end

  def can_attend?
    membership.can_attend
  end

  def membership_rights
    membership.all_rights
  end

  def dob_required?
    membership.dob_required?
  end

  def offer_for_purchase?
    !membership.private_membership_option
  end
end
