---
name: "Test pull requests"

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Extract PR number
        shell: bash
        run: echo "##[set-output name=branch;]$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
        id: extract_name

      - name: Define the repository labels
        run: |
          echo "CONTAINER_TEST_REPOSITORY=ci-pr-${{ steps.extract_name.outputs.branch }}" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build  --target=development --pull -t $CONTAINER_TEST_REPOSITORY .

      - name: Run specs
        run: |
          docker run -d --name="test-database" --hostname "postgres" -e "POSTGRES_PASSWORD=test" postgres:latest
          docker run --network "container:test-database" -e "POSTGRES_PASSWORD=test" $CONTAINER_TEST_REPOSITORY bundle exec rake db:create db:structure:load spec
